// Generated by gencpp from file picopter/CamMeasurement.msg
// DO NOT EDIT!


#ifndef PICOPTER_MESSAGE_CAMMEASUREMENT_H
#define PICOPTER_MESSAGE_CAMMEASUREMENT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace picopter
{
template <class ContainerAllocator>
struct CamMeasurement_
{
  typedef CamMeasurement_<ContainerAllocator> Type;

  CamMeasurement_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , yaw(0.0)
    , pitch(0.0)
    , roll(0.0)  {
    }
  CamMeasurement_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , yaw(0.0)
    , pitch(0.0)
    , roll(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;

   typedef double _yaw_type;
  _yaw_type yaw;

   typedef double _pitch_type;
  _pitch_type pitch;

   typedef double _roll_type;
  _roll_type roll;





  typedef boost::shared_ptr< ::picopter::CamMeasurement_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::picopter::CamMeasurement_<ContainerAllocator> const> ConstPtr;

}; // struct CamMeasurement_

typedef ::picopter::CamMeasurement_<std::allocator<void> > CamMeasurement;

typedef boost::shared_ptr< ::picopter::CamMeasurement > CamMeasurementPtr;
typedef boost::shared_ptr< ::picopter::CamMeasurement const> CamMeasurementConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::picopter::CamMeasurement_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::picopter::CamMeasurement_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace picopter

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'picopter': ['/home/pi/picopter/src/picopter/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::picopter::CamMeasurement_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::picopter::CamMeasurement_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::picopter::CamMeasurement_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::picopter::CamMeasurement_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::picopter::CamMeasurement_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::picopter::CamMeasurement_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::picopter::CamMeasurement_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b06e8d830a2510784fab4c15f68df674";
  }

  static const char* value(const ::picopter::CamMeasurement_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb06e8d830a251078ULL;
  static const uint64_t static_value2 = 0x4fab4c15f68df674ULL;
};

template<class ContainerAllocator>
struct DataType< ::picopter::CamMeasurement_<ContainerAllocator> >
{
  static const char* value()
  {
    return "picopter/CamMeasurement";
  }

  static const char* value(const ::picopter::CamMeasurement_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::picopter::CamMeasurement_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n\
float64 y\n\
float64 z\n\
float64 yaw\n\
float64 pitch\n\
float64 roll\n\
";
  }

  static const char* value(const ::picopter::CamMeasurement_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::picopter::CamMeasurement_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.yaw);
      stream.next(m.pitch);
      stream.next(m.roll);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CamMeasurement_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::picopter::CamMeasurement_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::picopter::CamMeasurement_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
    s << indent << "pitch: ";
    Printer<double>::stream(s, indent + "  ", v.pitch);
    s << indent << "roll: ";
    Printer<double>::stream(s, indent + "  ", v.roll);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PICOPTER_MESSAGE_CAMMEASUREMENT_H
