// Generated by gencpp from file picopter/SpinRates.msg
// DO NOT EDIT!


#ifndef PICOPTER_MESSAGE_SPINRATES_H
#define PICOPTER_MESSAGE_SPINRATES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace picopter
{
template <class ContainerAllocator>
struct SpinRates_
{
  typedef SpinRates_<ContainerAllocator> Type;

  SpinRates_()
    : motor_one(0.0)
    , motor_two(0.0)
    , motor_three(0.0)
    , motor_four(0.0)  {
    }
  SpinRates_(const ContainerAllocator& _alloc)
    : motor_one(0.0)
    , motor_two(0.0)
    , motor_three(0.0)
    , motor_four(0.0)  {
  (void)_alloc;
    }



   typedef double _motor_one_type;
  _motor_one_type motor_one;

   typedef double _motor_two_type;
  _motor_two_type motor_two;

   typedef double _motor_three_type;
  _motor_three_type motor_three;

   typedef double _motor_four_type;
  _motor_four_type motor_four;





  typedef boost::shared_ptr< ::picopter::SpinRates_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::picopter::SpinRates_<ContainerAllocator> const> ConstPtr;

}; // struct SpinRates_

typedef ::picopter::SpinRates_<std::allocator<void> > SpinRates;

typedef boost::shared_ptr< ::picopter::SpinRates > SpinRatesPtr;
typedef boost::shared_ptr< ::picopter::SpinRates const> SpinRatesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::picopter::SpinRates_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::picopter::SpinRates_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace picopter

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'picopter': ['/home/pi/picopter/src/picopter/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::picopter::SpinRates_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::picopter::SpinRates_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::picopter::SpinRates_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::picopter::SpinRates_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::picopter::SpinRates_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::picopter::SpinRates_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::picopter::SpinRates_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fb6650b063ad3f7904bcf518d546f7ec";
  }

  static const char* value(const ::picopter::SpinRates_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfb6650b063ad3f79ULL;
  static const uint64_t static_value2 = 0x04bcf518d546f7ecULL;
};

template<class ContainerAllocator>
struct DataType< ::picopter::SpinRates_<ContainerAllocator> >
{
  static const char* value()
  {
    return "picopter/SpinRates";
  }

  static const char* value(const ::picopter::SpinRates_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::picopter::SpinRates_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 motor_one\n\
float64 motor_two\n\
float64 motor_three\n\
float64 motor_four\n\
";
  }

  static const char* value(const ::picopter::SpinRates_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::picopter::SpinRates_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.motor_one);
      stream.next(m.motor_two);
      stream.next(m.motor_three);
      stream.next(m.motor_four);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SpinRates_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::picopter::SpinRates_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::picopter::SpinRates_<ContainerAllocator>& v)
  {
    s << indent << "motor_one: ";
    Printer<double>::stream(s, indent + "  ", v.motor_one);
    s << indent << "motor_two: ";
    Printer<double>::stream(s, indent + "  ", v.motor_two);
    s << indent << "motor_three: ";
    Printer<double>::stream(s, indent + "  ", v.motor_three);
    s << indent << "motor_four: ";
    Printer<double>::stream(s, indent + "  ", v.motor_four);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PICOPTER_MESSAGE_SPINRATES_H
